baseurl = "https://sophare.fr"
disqusShortname = ""
googleAnalytics = ""
languageCode = "fr-fr"
paginate = 5
preserveTaxonomyNames = true
theme = "hugo-nederburg-theme"
title = "So Phare"
[[menu.main]]
name = "Accueil"
url = "accueil/"
weight = 1
[[menu.main]]
name = "Contact"
url = "contact/"
weight = 3
[[menu.main]]
name = "À propos"
url = "about/"
weight = 2
[params]
author = ""
authorLink = "https://paulinespring.github.io/portfolio"
bio = ["Göran is an avid blogger and the founder of <a href='https://paulinespring.github.io/portfolio/'>Appernetic.io</a>. This is the author bio shown after posts."]
copyright = ["&copy; 2019 So phare", "By [Pauline Plessier](https://paulinespring.github.io/portfolio).", "Fait par moi"]
description = "Describe your website"
email = "goran@molnsys.com"
slogan = "Rédaction web et services SEO"
[params.social]
email = "email@example.com"
facebook = "full Social profile url in facebook"
github = "full profile url in github"
googleplus = "full profile url in googleplus"
instagram = "full profile url in instagram"
linkedin = "full profile url in linkedin"
pinterest = "full profile url in pinterest"
rss = true
stackoverflow = "full profile url in stackoverflow"
twitter = "full profile url in twitter"
[params.writers."Göran Svensson"]
bio = ["Göran is an avid blogger and the founder of <a href='https://paulinespring.github.io/portfolio/'>Appernetic.io</a>. This is the author bio shown after posts."]
email = "goran@molnsys.com"
facebook = "full Göran profile url in facebook"
github = "full profile url in github"
googleplus = "full profile url in googleplus"
instagram = "full profile url in instagram"
link = "https://paulinespring.github.io/portfolio/"
linkedin = "full profile url in linkedin"
pinterest = "full profile url in pinterest"
stackoverflow = "full profile url in stackoverflow"
twitter = "full profile url in twitter"
[params.writers."Lukas Herman"]
bio = ["Lukas has a few skills up his sleve. He can fly blindfolded under a bridge while simultanous writing blog posts."]
email = "lherman.cs@gmail.com"
facebook = "full lukas profile url in facebook"
github = "full profile url in github"
googleplus = "full profile url in googleplus"
instagram = "full profile url in instagram"
link = "https://lherman.tk"
linkedin = "full profile url in linkedin"
pinterest = "full profile url in pinterest"
stackoverflow = "full profile url in stackoverflow"
twitter = "full profile url in twitter"
[privacy.googleAnalytics]
anonymizeIP = false
disable = false
respectDoNotTrack = false
useSessionStorage = false
